<a href="https://colab.research.google.com/github/JAntonioRosales/matrix_exercise/blob/main/ZF_algorithm_engineer_matrix_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOSÃ‰ ANTONIO ROSALES MEDINA

In [64]:
import pandas as pd
import numpy as np

### Loading

In [65]:
# Loading the data
data = pd.read_csv("https://raw.githubusercontent.com/JAntonioRosales/matrix_exercise/main/perimetro-suma-cero.csv", header=None)
data

    0   1   2   3   4   5   6   7   8   9   10  11  12
0   19  -9 -16  -6 -35   5   6  23  42  22  18 -32  -5
1   46 -34  -4 -48  15   4  13  16 -28  -8 -24  34  31
2  -43  11   8 -18  -7 -45   1 -19 -45  48 -13 -21  39
3  -24   8 -46 -22  20 -21 -21  26  18 -35  -8   8 -10
4  -29  21 -19   6  10 -47  17 -21 -10  44  35  16 -21
5   35  -9 -28 -27 -39 -42 -34 -49 -45 -19  21  30 -42
6  -17 -23 -48 -10 -39  21 -21 -49 -14 -35 -17 -28 -47
7  -10 -14   1 -47  26 -43  47 -35 -23  -9  16 -30  26
8  -49  13   6   8  37  38   9 -26  29  -3  45  44  44
9  -20 -38 -29 -37  11   8 -43 -42  29 -46 -25 -32 -47
10  10  27  26  12  21  35 -48 -30 -44   4  45 -28  37
11  -2 -13 -10  10  41  -1 -47  44  11  40   6 -37 -19
12 -26  -2 -45  -3  22  47  47  20  29 -16 -42  -1  26
13  46  33 -22   0 -14 -26 -45  25 -22 -35 -33  22  -3
14 -18 -18 -23  10  43  26  48  25 -14 -50 -18 -14 -33
15   7 -27  44 -49  18 -28  -2  42 -43 -16  -8 -50 -35
16 -24  48  38 -46 -49   3 -35  -3 -26 -25  17  28 -10
17  -2 -24 -23  30 -32 -49  47 -39 -37  20 -24 -23 -49
18  48  44 -49 -28  41 -48  11 -29  39  29  42  32 -37
19   7  28  -3  42  -8 -15 -40   6 -38 -48  35  41   7
20  24 -34  33 -40 -17  43  40  47  47 -24  14  -5  27
21 -12  33  48  31   2 -31 -40  10  17   0  26 -46 -40
22 -21  -9 -11 -19  46  13  19  37  22   7  -6 -20  47
23  21 -49  46 -16   3 -14  40 -29  45 -33  11  38  -4
24 -24 -42  18 -11 -16 -41  10  41 -14  22  39 -43  20
25 -42  13 -39 -12  41 -14 -28   9  -2 -24 -21 -15  -5

In [66]:
# Convert to numpy array
mat = data.to_numpy()
mat

array([[ 19,  -9, -16,  -6, -35,   5,   6,  23,  42,  22,  18, -32,  -5],
       [ 46, -34,  -4, -48,  15,   4,  13,  16, -28,  -8, -24,  34,  31],
       [-43,  11,   8, -18,  -7, -45,   1, -19, -45,  48, -13, -21,  39],
       [-24,   8, -46, -22,  20, -21, -21,  26,  18, -35,  -8,   8, -10],
       [-29,  21, -19,   6,  10, -47,  17, -21, -10,  44,  35,  16, -21],
       [ 35,  -9, -28, -27, -39, -42, -34, -49, -45, -19,  21,  30, -42],
       [-17, -23, -48, -10, -39,  21, -21, -49, -14, -35, -17, -28, -47],
       [-10, -14,   1, -47,  26, -43,  47, -35, -23,  -9,  16, -30,  26],
       [-49,  13,   6,   8,  37,  38,   9, -26,  29,  -3,  45,  44,  44],
       [-20, -38, -29, -37,  11,   8, -43, -42,  29, -46, -25, -32, -47],
       [ 10,  27,  26,  12,  21,  35, -48, -30, -44,   4,  45, -28,  37],
       [ -2, -13, -10,  10,  41,  -1, -47,  44,  11,  40,   6, -37, -19],
       [-26,  -2, -45,  -3,  22,  47,  47,  20,  29, -16, -42,  -1,  26],
       [ 46,  33, -22,   0, -14, -26, -45,  25, -22, -35, -33,  22,  -3],
       [-18, -18, -23,  10,  43,  26,  48,  25, -14, -50, -18, -14, -33],
       [  7, -27,  44, -49,  18, -28,  -2,  42, -43, -16,  -8, -50, -35],
       [-24,  48,  38, -46, -49,   3, -35,  -3, -26, -25,  17,  28, -10],
       [ -2, -24, -23,  30, -32, -49,  47, -39, -37,  20, -24, -23, -49],
       [ 48,  44, -49, -28,  41, -48,  11, -29,  39,  29,  42,  32, -37],
       [  7,  28,  -3,  42,  -8, -15, -40,   6, -38, -48,  35,  41,   7],
       [ 24, -34,  33, -40, -17,  43,  40,  47,  47, -24,  14,  -5,  27],
       [-12,  33,  48,  31,   2, -31, -40,  10,  17,   0,  26, -46, -40],
       [-21,  -9, -11, -19,  46,  13,  19,  37,  22,   7,  -6, -20,  47],
       [ 21, -49,  46, -16,   3, -14,  40, -29,  45, -33,  11,  38,  -4],
       [-24, -42,  18, -11, -16, -41,  10,  41, -14,  22,  39, -43,  20],
       [-42,  13, -39, -12,  41, -14, -28,   9,  -2, -24, -21, -15,  -5]])

In [67]:
# Verify matrix shape
m_shape = mat.shape
m_shape

(26, 13)

We have a 26 x 13 matrix.

### Testing

In [103]:
# ------------------ TESTING ------------------

# Extracts any matrix from any given position in the original matrix.

# ONLY internal - MODIFY
r = 4
c = 4

# Increased items
real_r = r + 1
real_c = c + 1

# Initial item - MODIFY
init_r = 21
init_c = 8

# ONLY for the end result
real_init_r = init_r + 1
real_init_c = init_c + 1

# Controlling over-sized matrices
space_rows = rows - init_r
space_cols = cols - init_c
print("Largest possible matrix:",space_rows,"x",space_cols)

if real_r <= space_rows and real_c <= space_cols:
  print("YES")
  submat = mat[init_r:init_r+real_r,init_c:init_c+real_c]
  print(submat)
else:
  print("NO")

Largest possible matrix: 5 x 5
YES
[[ 17   0  26 -46 -40]
 [ 22   7  -6 -20  47]
 [ 45 -33  11  38  -4]
 [-14  22  39 -43  20]
 [ -2 -24 -21 -15  -5]]

In [118]:
left = submat[:,0]
sum_l = np.sum(left)
right = submat[:,-1]
sum_r = np.sum(right)
top = submat[0,:]
sum_t = np.sum(top)
bottom = submat[-1,:]
sum_b = np.sum(bottom)
sum = sum_l + sum_r + sum_t + sum_b
print(sum)

-24

### Implementation

In [119]:
def calc_perimeter(mat, init_r, real_r, init_c, real_c):
  
  # Retrieve submatrix
  submat = mat[init_r:init_r+real_r,init_c:init_c+real_c]
  
  # Sum the perimeter
  left = submat[:,0]
  right = submat[:,-1]
  top = submat[0,:]
  bottom = submat[-1,:]
  sum = np.sum(left) + np.sum(right) + np.sum(top) + np.sum(bottom)
  
  return sum

In [120]:
# Establish limit of rows and columns
rows = m_shape[0]
cols = m_shape[1]

# Initialize empty lists
init_row = []
init_col = []
m = []
n = []

for r in range(rows):
  for c in range(cols):

    # Python begins indexing at 0
    real_r = r + 1
    real_c = c + 1

    # Show submatrix size
    print(r,"x",c)

    # Traverse the matrix
    for init_r in range(rows):
      for init_c in range(cols):

        # Python begins indexing at 0
        real_init_r = init_r + 1
        real_init_c = init_c + 1

        # Determining available space in the matrix from starting point
        space_rows = rows - init_r
        space_cols = cols - init_c

        # If there's enough space
        if real_r <= space_rows and real_c <= space_cols:
          
          # Case when matrix is 1x1
          if real_r == 1 and real_c == 1:
            val = mat[init_r,init_c]

          # Case when matrix is larger than 1x1
          else:
            val = calc_perimeter(mat, init_r, real_r, init_c, real_c)

          if val == 0:
            init_row.append(real_init_r)
            init_col.append(real_init_c)
            m.append(real_r)
            n.append(real_c)
        
        # Ignoring over-sized matrices for starting point
        else:
          continue

0 x 0
0 x 1
0 x 2
0 x 3
0 x 4
0 x 5
0 x 6
0 x 7
0 x 8
0 x 9
0 x 10
0 x 11
0 x 12
1 x 0
1 x 1
1 x 2
1 x 3
1 x 4
1 x 5
1 x 6
1 x 7
1 x 8
1 x 9
1 x 10
1 x 11
1 x 12
2 x 0
2 x 1
2 x 2
2 x 3
2 x 4
2 x 5
2 x 6
2 x 7
2 x 8
2 x 9
2 x 10
2 x 11
2 x 12
3 x 0
3 x 1
3 x 2
3 x 3
3 x 4
3 x 5
3 x 6
3 x 7
3 x 8
3 x 9
3 x 10
3 x 11
3 x 12
4 x 0
4 x 1
4 x 2
4 x 3
4 x 4
4 x 5
4 x 6
4 x 7
4 x 8
4 x 9
4 x 10
4 x 11
4 x 12
5 x 0
5 x 1
5 x 2
5 x 3
5 x 4
5 x 5
5 x 6
5 x 7
5 x 8
5 x 9
5 x 10
5 x 11
5 x 12
6 x 0
6 x 1
6 x 2
6 x 3
6 x 4
6 x 5
6 x 6
6 x 7
6 x 8
6 x 9
6 x 10
6 x 11
6 x 12
7 x 0
7 x 1
7 x 2
7 x 3
7 x 4
7 x 5
7 x 6
7 x 7
7 x 8
7 x 9
7 x 10
7 x 11
7 x 12
8 x 0
8 x 1
8 x 2
8 x 3
8 x 4
8 x 5
8 x 6
8 x 7
8 x 8
8 x 9
8 x 10
8 x 11
8 x 12
9 x 0
9 x 1
9 x 2
9 x 3
9 x 4
9 x 5
9 x 6
9 x 7
9 x 8
9 x 9
9 x 10
9 x 11
9 x 12
10 x 0
10 x 1
10 x 2
10 x 3
10 x 4
10 x 5
10 x 6
10 x 7
10 x 8
10 x 9
10 x 10
10 x 11
10 x 12
11 x 0
11 x 1
11 x 2
11 x 3
11 x 4
11 x 5
11 x 6
11 x 7
11 x 8
11 x 9
11 x 10
11 x 11
11 x 12
12 x 0
12 x 1
12 x 2
12 x 3
12 x 4
12 x 5
12 x 6
12 x 7
12 x 8
12 x 9
12 x 10
12 x 11
12 x 12
13 x 0
13 x 1
13 x 2
13 x 3
13 x 4
13 x 5
13 x 6
13 x 7
13 x 8
13 x 9
13 x 10
13 x 11
13 x 12
14 x 0
14 x 1
14 x 2
14 x 3
14 x 4
14 x 5
14 x 6
14 x 7
14 x 8
14 x 9
14 x 10
14 x 11
14 x 12
15 x 0
15 x 1
15 x 2
15 x 3
15 x 4
15 x 5
15 x 6
15 x 7
15 x 8
15 x 9
15 x 10
15 x 11
15 x 12
16 x 0
16 x 1
16 x 2
16 x 3
16 x 4
16 x 5
16 x 6
16 x 7
16 x 8
16 x 9
16 x 10
16 x 11
16 x 12
17 x 0
17 x 1
17 x 2
17 x 3
17 x 4
17 x 5
17 x 6
17 x 7
17 x 8
17 x 9
17 x 10
17 x 11
17 x 12
18 x 0
18 x 1
18 x 2
18 x 3
18 x 4
18 x 5
18 x 6
18 x 7
18 x 8
18 x 9
18 x 10
18 x 11
18 x 12
19 x 0
19 x 1
19 x 2
19 x 3
19 x 4
19 x 5
19 x 6
19 x 7
19 x 8
19 x 9
19 x 10
19 x 11
19 x 12
20 x 0
20 x 1
20 x 2
20 x 3
20 x 4
20 x 5
20 x 6
20 x 7
20 x 8
20 x 9
20 x 10
20 x 11
20 x 12
21 x 0
21 x 1
21 x 2
21 x 3
21 x 4
21 x 5
21 x 6
21 x 7
21 x 8
21 x 9
21 x 10
21 x 11
21 x 12
22 x 0
22 x 1
22 x 2
22 x 3
22 x 4
22 x 5
22 x 6
22 x 7
22 x 8
22 x 9
22 x 10
22 x 11
22 x 12
23 x 0
23 x 1
23 x 2
23 x 3
23 x 4
23 x 5
23 x 6
23 x 7
23 x 8
23 x 9
23 x 10
23 x 11
23 x 12
24 x 0
24 x 1
24 x 2
24 x 3
24 x 4
24 x 5
24 x 6
24 x 7
24 x 8
24 x 9
24 x 10
24 x 11
24 x 12
25 x 0
25 x 1
25 x 2
25 x 3
25 x 4
25 x 5
25 x 6
25 x 7
25 x 8
25 x 9
25 x 10
25 x 11
25 x 12

In [121]:
print(init_row)
print(init_col)
print(m)
print(n)

[14, 22, 4, 7, 12, 8, 12, 14, 20, 21, 23, 23, 11, 9, 15, 24, 13, 2, 11, 9, 12, 9, 5, 17, 22, 12, 17, 16, 23, 21, 12, 17, 11, 1, 1, 4, 4, 9, 18, 18, 17, 12, 7, 19, 15, 11, 9, 16, 12, 18, 4, 6, 9, 10, 15, 15, 5, 9, 2, 9, 9, 1, 11, 1, 2, 11, 2, 4, 5]
[4, 10, 11, 6, 3, 5, 7, 6, 7, 7, 1, 3, 9, 5, 3, 4, 1, 8, 1, 6, 2, 3, 7, 9, 9, 3, 8, 5, 2, 1, 5, 4, 2, 9, 7, 1, 1, 12, 1, 6, 8, 8, 4, 6, 2, 6, 7, 1, 12, 3, 7, 6, 6, 11, 6, 8, 3, 9, 6, 3, 9, 11, 1, 6, 5, 6, 1, 5, 1]
[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 9, 9, 10, 11, 11, 11, 11, 11, 12, 12, 12, 13, 14, 14, 15, 15, 15, 16, 20, 21, 22]
[1, 1, 2, 2, 2, 7, 1, 1, 1, 1, 1, 2, 5, 6, 9, 9, 12, 2, 4, 5, 8, 2, 4, 4, 4, 5, 5, 6, 12, 7, 8, 9, 1, 3, 6, 11, 12, 2, 2, 2, 3, 5, 6, 8, 12, 1, 2, 10, 1, 5, 5, 1, 1, 1, 2, 3, 3, 4, 7, 8, 1, 3, 2, 3, 5, 3, 5, 2, 5]

In [131]:
# Empty list for sizes
sizes = []

# Calculate the size of the matrices
for i in range(len(m)):
  m_val = m[i]
  n_val = n[i]
  mat_size = m_val*n_val
  sizes.append(mat_size)

In [138]:
# Find the largest matrix
largest = max(sizes)
largest_idx = sizes.index(largest)
print("Largest matrix:", largest)
print("Index:", largest_idx)

Largest matrix: 110
Index: 68

In [140]:
IR = init_row[largest_idx]
IC = init_col[largest_idx]
M = m[largest_idx]
N = n[largest_idx]
print("The largest matrix whose perimeter equals 0 is a",M,"x",N,"matrix starting at [",IR,",",IC,"] (normal notation, not Python)")

The largest matrix whose perimeter equals 0 is a 22 x 5 matrix starting at [ 5 , 1 ] (normal notation, not Python)